// <auto-generated />
namespace Tasks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DelStatus1FromDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelStatus1FromDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202109070903051_DelStatus1FromDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
